In [1]:
import pandas as pd

In [2]:
file_path = 'SI_2_Material_requirements.xlsx'
xls = pd.ExcelFile(file_path)

In [3]:
sheets_to_exclude = ["Materials", "Technologies", "References"]
sheets_to_include = [sheet for sheet in xls.sheet_names if sheet not in sheets_to_exclude]

In [4]:
combined_df = pd.DataFrame(columns=["metal", "unit", "year", "mean", "median", "min", "max", "origin_var"])

In [5]:
for sheet in sheets_to_include:
    df = pd.read_excel(file_path, sheet_name=sheet, skiprows=2, header=None, usecols="A:G")
    df.columns = ['metal', 'unit', 'year', 'mean', 'median', 'min', 'max']
    df = df.dropna(how='all')
    df = df[df['metal'] != 'mean']
    df["origin_var"] = sheet
    
    combined_df = pd.concat([combined_df, df], ignore_index=True)
    
combined_df

C:\Users\hahnme_a\AppData\Local\Temp\ipykernel_20220\936690025.py:8: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_df = pd.concat([combined_df, df], ignore_index=True)

,metal,unit,year,mean,median,min,max,origin_var
0,Aluminium,kg metal/kg vehicle,2020.0,0.245611,0.245611,2.456112e-01,0.245611,ICEV
1,Antimony,kg metal/kg vehicle,2020.0,0.001169,0.001134,7.428823e-04,0.001660,ICEV
2,Beryllium,kg metal/kg vehicle,2020.0,0.000003,0.000003,1.620822e-06,0.000004,ICEV
3,Cerium,kg metal/kg vehicle,2020.0,0.000016,0.000013,1.550000e-07,0.000049,ICEV
4,Cobalt,kg metal/kg vehicle,2020.0,0.003039,0.003562,1.948080e-03,0.003737,ICEV
...,...,...,...,...,...,...,...,...
236,Praseodimium,kg/MW,2020.0,8.784196,8.784196,8.784196e+00,8.784196,HTEL - Yttrium
237,Strontium,kg/MW,2020.0,2.737974,2.396332,1.616888e+00,4.200702,HTEL - Yttrium
238,Yttrium,kg/MW,2020.0,50.875605,65.997099,1.156334e+01,75.066370,HTEL - Yttrium
239,Zirconium,kg/MW,2020.0,242.987230,271.390647,6.822289e+01,389.348155,HTEL - Yttrium
240,Yttrium,kg/MW,2050.0,6.016672,6.016672,4.700000e-01,11.563345,HTEL - Yttrium

In [6]:
output_file = 'metals_db.csv'
combined_df.to_csv(output_file, index=False)